version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/usr/src/app  # Mounts the entire application directory
      - persistent-data:/usr/src/app  # Persistent volume for shared data
    environment:
      - FLASK_ENV=development

  searcher:
    build: .
    command: python3 subito-searcher.py --daemon
    volumes:
      - .:/usr/src/app  # Mounts the entire application directory
      - persistent-data:/usr/src/app  # Persistent volume for shared data

volumes:
  persistent-data: